export {
  CURRENT_FORMAT_VERSION,
  READABLE_FORMAT_VERSIONS,
  StoreFormatError,
  emptyDocument,
  migrateDocument,
  parseStoreDocument,
  storeDocumentSchema,
  type StoreDocument,
  type StoredBalanceSnapshot,
  type StoredCashflowItem,
  type StoredDebtEvent,
  type StoredTransaction,
} from './document';

export {
  DATA_DIRECTORY,
  PathEscapeError,
  resolveStorePaths,
  safeJoin,
  uploadFileName,
  type StorePaths,
} from './paths';

export {
  ConcurrentModificationError,
  FileStore,
  StoreNotInitialisedError,
  type StoreSnapshot,
} from './file-store';

export { auditEvent, reduce, withAudit, type AuditInput } from './audit';

export {
  addCheck,
  addCheckSeries,
  cancelCheck,
  checksForDebt,
  clearCheck,
  closeLoan,
  closeLoanBlockers,
  deliverChecks,
  markCheckDeposited,
  markCheckReturned,
  plannedRepaymentTotal,
  previewCheckSeries,
  replaceCheck,
  requireCheck,
  revertCheckStatus,
  setRepaymentPlan,
  type AddCheckInput,
  type AddCheckSeriesInput,
  type ClearCheckInput,
  type CloseLoanBlockers,
  type ClearCheckOutcome,
  type DeliverChecksInput,
  type ReplaceCheckInput,
  type ResolveCheckInput,
  type RevertCheckInput,
  type SetRepaymentPlanInput,
} from './checks';

export {
  MATCH_WINDOW_AFTER_DAYS,
  MATCH_WINDOW_BEFORE_DAYS,
  digitRunsIn,
  looksLikeCheckDebit,
  matchesForDebit,
  proposeCheckMatch,
  type CheckMatch,
  type CheckMatchProposal,
  type CheckMatchReason,
  type DebitCandidate,
} from './check-match';

export {
  ALL_BUDGET_CATEGORY_KEYS,
  CommandError,
  acceptReconciliationGap,
  addAccount,
  addBusiness,
  addDebt,
  addMember,
  addPlannedItem,
  addTask,
  categoryNameFor,
  closeAccount,
  declareNoBusiness,
  recordBalance,
  recordDebtEvent,
  recordRollover,
  recordTransaction,
  removePlannedItem,
  renameHousehold,
  setBudgetLine,
  settlePlannedItem,
  startBudget,
  transferToHousehold,
  updateSettings,
  updateTask,
  voidTransaction,
  type AddAccountInput,
  type AddBusinessInput,
  type AddDebtInput,
  type AddMemberInput,
  type AddPlannedItemInput,
  type AddTaskInput,
  type CommandContext,
  type CommandResult,
  type RecordBalanceInput,
  type RecordDebtEventInput,
  type RecordRolloverInput,
  type RecordTransactionInput,
  type SetBudgetLineInput,
  type StartBudgetInput,
  type TransferToHouseholdInput,
  type UpdateSettingsInput,
  type UpdateTaskInput,
  type VoidTransactionInput,
} from './commands';

export {
  alreadyImported,
  approveBatch,
  checkApproval,
  rejectBatch,
  reverseBatch,
  reviewAll,
  reviewProposal,
  stageExtraction,
  stageFailure,
  type ApprovalCheck,
  type ApprovalOutcome,
  type ReversalOutcome,
  type ReviewProposalInput,
  type StageExtractionInput,
  type StageFailureInput,
} from './imports';

export {
  activeLearnedRules,
  addLearnedRule,
  deleteLearnedRule,
  noteRuleApplied,
  updateLearnedRule,
  type UpdateLearnedRuleInput,
} from './learned-rules';

export {
  BACKUP_ENVELOPE_VERSION,
  BackupError,
  backupFileName,
  checksumOf,
  createBackup,
  documentToRestore,
  previewRestore,
  serialiseBackup,
  summarise,
  type BackupEnvelope,
  type BackupSummary,
  type RestorePreview,
} from './backup';

export {
  balanceOf,
  categoryIdFor,
  dataAgeDays,
  isPendingTransaction,
  isRealTransaction,
  periodEndFor,
  periodKey,
  pendingImportRowCount,
  periodStartFor,
  startOfWeek,
  toBudgetInput,
  toEngineInput,
  toFoodWeekInput,
  type AccountBalance,
  type ProjectionOptions,
} from './projection';

export { HouseholdStore, viewOf, type CreateHouseholdInput, type HouseholdView } from './store';
