import { count, formatBusinessDate, money } from '../format';

/**
 * The words for everything the family can do, as opposed to everything they can
 * see.
 *
 * `copy.ts` describes the financial picture. This describes the workflows around
 * it — setting up, typing an expense, uploading a statement, reviewing what it
 * said, approving it, exporting, backing up. Kept apart because the two are read
 * by different people at different moments and reviewed for different things: one
 * has to be accurate, the other has to be doable at nine in the evening with a
 * child asking for something.
 *
 * Every label here is written to answer three questions in order: what is this,
 * why does it matter, what do I do now. A field called "certainty" fails all
 * three; "עד כמה זה בטוח" answers the first two and the options answer the third.
 */

export const screens = {
  setup: {
    title: 'בואו נתחיל',
    intro:
      'כמה פרטים כדי שהמסכים יראו את התמונה שלכם. אפשר לעצור בכל שלב ולהמשיך אחר כך — שום דבר לא נמחק.',
    householdName: 'איך לקרוא למשק הבית',
    householdNameHint: 'למשל: הבית של דנה ויוסי',
    yourName: 'איך קוראים לכם',
    create: 'ליצור את משק הבית',
    created: 'משק הבית נוצר',
    progressTitle: 'עד כמה השלמנו',
    progress: (done: number, total: number) => `${count(done)} מתוך ${count(total)} שלבים`,
    steps: {
      householdNamed: 'שם למשק הבית',
      membersAdded: 'מי גר כאן',
      accountsAdded: 'חשבונות וכרטיסים',
      balancesConfirmed: 'כמה יש עכשיו בכל חשבון',
      businessDecided: 'האם יש עסק',
      debtsRecorded: 'חובות והלוואות',
      recurringIncomeRecorded: 'כסף שנכנס בכל חודש',
      recurringObligationsRecorded: 'תשלומים קבועים',
      budgetStarted: 'תקציב לחודש',
      privacyExplained: 'איפה הנתונים נשמרים',
    } as Record<string, string>,
    stepDone: 'הושלם',
    stepOpen: 'עוד לא',
    members: 'מי גר כאן',
    membersHint: 'כדי שאפשר יהיה לחלק משימות ביניכם.',
    addMember: 'להוסיף בן או בת משפחה',
    memberName: 'שם',
    businessTitle: 'יש לכם עסק?',
    businessHint:
      'אם יש, נחזיק את הכסף שלו בנפרד — כדי שלא ייראה כאילו כסף של מסים או של ספקים זמין לבית.',
    businessName: 'שם העסק',
    businessTaxRate: 'כמה אחוז לשמור למסים',
    businessTaxRateHint: 'הערכה סבירה מספיקה. אפשר לשנות בכל רגע.',
    businessReserve: 'כמה העסק חייב להשאיר אצלו',
    businessReserveHint: 'הכסף שמאפשר לעסק להמשיך לעבוד גם בחודש חלש.',
    addBusiness: 'להוסיף עסק',
    noBusiness: 'אין לנו עסק',
    noBusinessDone: 'סימנו שאין עסק. אפשר לשנות בכל רגע.',
    privacyTitle: 'איפה הנתונים נשמרים',
    privacyBody:
      'הכול נשמר על המחשב הזה בלבד, בתיקייה בתוך התוכנה. שום מספר לא נשלח לשום מקום, ואין חיבור לבנק ולא לשירות חיצוני. גיבוי נוצר רק כשאתם מבקשים.',
    privacyAck: 'הבנו',
    finish: 'זהו, אפשר להתחיל',
  },

  accounts: {
    title: 'חשבונות וכרטיסים',
    subtitle: 'איפה הכסף נמצא, וכמה יש בכל מקום',
    empty: 'עוד לא הוספתם חשבון.',
    emptyHint: 'נתחיל מהעובר ושב — זה מספיק כדי לראות תמונה ראשונה.',
    add: 'להוסיף חשבון',
    name: 'איך לקרוא לחשבון',
    nameHint: 'למשל: עובר ושב, כרטיס ויזה, מזומן',
    kind: 'סוג',
    kinds: {
      bank_account: 'חשבון בנק',
      credit_card: 'כרטיס אשראי',
      cash_wallet: 'מזומן',
      other: 'אחר',
    } as Record<string, string>,
    scope: 'שייך ל',
    scopes: { household: 'הבית', business: 'העסק' } as Record<string, string>,
    institution: 'בנק או חברה',
    suffix: 'ארבע ספרות אחרונות',
    suffixHint: 'רק ארבע ספרות, כדי לזהות את הכרטיס. אנחנו לא שומרים מספר מלא.',
    opening: 'כמה יש שם עכשיו',
    openingDirection: 'מה זה הסכום',
    directionHave: 'כסף שיש',
    directionOwe: 'כסף שחייבים',
    openingDate: 'נכון לתאריך',
    balanceNow: 'לפי מה שרשום',
    confirmed: 'אושר מול הבנק',
    neverConfirmed: 'עוד לא אושר מול הבנק',
    confirmedOn: (date: string) => `אושר ב־${formatBusinessDate(date)}`,
    updateBalance: 'לעדכן יתרה',
    updateBalanceHint: 'להיכנס לאפליקציה של הבנק ולהעתיק את המספר. זה מה שמדייק את כל השאר.',
    balanceValue: 'היתרה עכשיו',
    balanceDate: 'נכון לתאריך',
    balanceNote: 'הערה',
    saveBalance: 'לשמור את היתרה',
    gapTitle: 'יש הפרש',
    gapExplain: (amountMinor: number) =>
      `לפי מה שרשום אצלנו אמור להיות הפרש של ${money(amountMinor)} מול מה שהבנק אמר.`,
    gapWhat:
      'זה קורה כשמשהו לא נרשם, או נרשם פעמיים. אפשר לחפש מה חסר, או לסגור את ההפרש כתיקון.',
    gapAccept: 'לסגור את ההפרש כתיקון',
    gapAcceptNote: 'התיקון נרשם בנפרד ואינו נחשב הוצאה.',
    close: 'לסגור את החשבון',
    closeHint: 'ההיסטוריה נשמרת. החשבון פשוט מפסיק להופיע בתמונה הנוכחית.',
    closed: 'סגור',
  },

  entry: {
    title: 'רישום מהיר',
    subtitle: 'מה שקרה היום, בלי למלא טפסים ארוכים',
    tabs: {
      expense: 'הוצאה',
      income: 'הכנסה',
      movement: 'העברה בין חשבונות',
      planned: 'משהו שצפוי',
      debt: 'תשלום על חוב',
    } as Record<string, string>,
    expenseTitle: 'מה יצא',
    incomeTitle: 'מה נכנס',
    movementTitle: 'העברה בין החשבונות שלכם',
    movementHint:
      'העברה בין החשבונות שלכם אינה הוצאה. גם תשלום של כרטיס אשראי מהבנק אינו הוצאה נוספת — ההוצאה כבר נרשמה כשקנו.',
    plannedTitle: 'משהו שעוד לא קרה',
    plannedHint: 'זה מה שמאפשר לדעת מה צפוי עד סוף החודש.',
    debtTitle: 'תשלום על חוב',
    debtHint:
      'הקרן והריבית נרשמות בנפרד. תשלום ריבית לא מקטין את החוב עצמו, ולכן הוא לא נספר כהתקדמות.',
    account: 'מאיזה חשבון',
    toAccount: 'לאיזה חשבון',
    amount: 'סכום',
    amountHint: 'אפשר לכתוב 1,250 או 1250.50',
    date: 'תאריך',
    merchant: 'על מה',
    merchantHint: 'למשל: סופר, דלק, ביטוח',
    from: 'ממי או ממה',
    category: 'קטגוריה',
    categoryNone: 'בלי קטגוריה',
    note: 'הערה',
    scope: 'שייך ל',
    movementKind: 'סוג',
    movementKinds: {
      transfer: 'העברה בין חשבונות',
      settlement: 'תשלום של כרטיס אשראי',
    } as Record<string, string>,
    label: 'על מה מדובר',
    direction: 'נכנס או יוצא',
    directions: { inflow: 'נכנס', outflow: 'יוצא' } as Record<string, string>,
    certainty: 'עד כמה זה בטוח',
    certainties: {
      certain: 'בטוח — כבר סגור',
      probable: 'כנראה — קרה כמעט תמיד',
      possible: 'אולי — לא הייתי סומך על זה',
    } as Record<string, string>,
    certaintyHint: 'רק "בטוח" נכנס לחישוב של כמה אפשר להוציא.',
    expectedDate: 'מתי זה צפוי',
    dueDate: 'תאריך אחרון לתשלום',
    essential: 'זה משהו חיוני',
    essentialHint: 'חיוני = אם לא ישולם, יקרה נזק אמיתי. אוכל, דיור, תרופות, משכנתה.',
    principal: 'על חשבון החוב עצמו',
    interest: 'ריבית ועמלות',
    save: 'לשמור',
    saved: 'נשמר',
    cancel: 'ביטול',
    needAccount: 'כדי לרשום, צריך קודם להוסיף חשבון אחד.',
    goToAccounts: 'להוספת חשבון',
  },

  upload: {
    title: 'העלאת מסמך',
    subtitle: 'דוח בנק, פירוט אשראי, לוח תשלומים או גיליון הוצאות',
    promise: 'שום דבר מהקובץ לא נכנס לחשבון לפני שתעברו עליו ותאשרו.',
    choose: 'לבחור קובץ',
    dropHint: 'אפשר גם לגרור קובץ לכאן',
    accepts: 'קבצים נתמכים: xlsx, csv, ו־PDF שאפשר לסמן בו טקסט.',
    limits: 'עד 20 מגה־בייט לקובץ.',
    account: 'לאיזה חשבון הקובץ שייך',
    accountHint: 'אפשר גם לבחור אחר כך, בזמן הבדיקה.',
    scope: 'שייך ל',
    upload: 'להעלות ולקרוא',
    reading: 'קוראים את הקובץ…',
    notScanned: 'הקובץ נקרא כאן במחשב בלבד ולא נשלח לשום מקום.',
    xlsNote: 'קובץ Excel ישן (xls) לא נקרא. אפשר לפתוח אותו ולשמור בשם כ־xlsx.',
    scanNote:
      'PDF סרוק הוא תמונה של דף, ואין בו טקסט לקריאה. אפשר להוריד מהבנק גרסה שאפשר לסמן בה טקסט, או להזין את השורות ידנית.',
    history: 'מה העלינו עד היום',
    noHistory: 'עוד לא העלינו קבצים.',
  },

  review: {
    title: 'מה נמצא בקובץ',
    subtitle: 'עוברים שורה שורה, מתקנים מה שצריך, ומאשרים',
    pending: 'ממתין לבדיקה ואישור',
    summaryTitle: 'סיכום הקריאה',
    file: 'הקובץ',
    documentType: 'סוג המסמך',
    documentTypes: {
      bank_statement: 'דוח תנועות בחשבון',
      credit_card_statement: 'פירוט חיובים בכרטיס',
      loan_schedule: 'לוח תשלומים של הלוואה',
      mortgage_schedule: 'לוח תשלומים של משכנתה',
      private_debt_list: 'רשימת חובות פרטיים',
      household_income_expense: 'הכנסות והוצאות של הבית',
      business_income_expense: 'הכנסות והוצאות של העסק',
      balance_summary: 'ריכוז יתרות',
      budget_file: 'קובץ תקציב',
      general_table: 'טבלה פיננסית',
      unrecognised: 'לא זיהינו את סוג המסמך',
    } as Record<string, string>,
    sheets: 'גיליונות',
    pages: 'עמודים',
    rowsFound: (found: number) => `${count(found)} שורות שנראות כמו תנועות`,
    rowsSkipped: (skipped: number) =>
      `${count(skipped)} שורות דולגו (ריקות, כותרות או סיכומים)`,
    dateRange: (start: string, end: string) =>
      `מ־${formatBusinessDate(start)} עד ${formatBusinessDate(end)}`,
    accountsFound: 'זוהו בקובץ',
    needsAttention: 'שורות שכדאי להסתכל עליהן',
    duplicates: 'שורות שנראות כמו משהו שכבר קיים',
    lowConfidence: 'לא היינו בטוחים',
    columnsTitle: 'איך קראנו את העמודות',
    columnRole: {
      transaction_date: 'תאריך',
      posting_date: 'תאריך חיוב',
      value_date: 'תאריך ערך',
      description: 'תיאור',
      debit: 'יצא',
      credit: 'נכנס',
      amount: 'סכום',
      balance: 'יתרה',
      principal: 'קרן',
      interest: 'ריבית',
      category: 'קטגוריה',
      account: 'חשבון',
      card: 'כרטיס',
      reference: 'אסמכתא',
      installment: 'תשלומים',
      currency: 'מטבע',
      notes: 'הערות',
      unknown: 'לא זיהינו',
    } as Record<string, string>,
    manualMapping: 'לא הצלחנו לזהות את העמודות בגיליון הזה. אפשר לעבור שורה שורה ולתקן.',
    rowsTitle: 'השורות',
    rowState: {
      pending: 'עוד לא הוכרע',
      included: 'ייכנס',
      excluded: 'לא ייכנס',
    } as Record<string, string>,
    include: 'להכניס',
    exclude: 'לא להכניס',
    includeAll: 'להכניס את כל מה שלא הוכרע',
    excludeAll: 'לא להכניס את מה שלא הוכרע',
    edit: 'לתקן',
    editTitle: 'לתקן את השורה',
    sourceTitle: 'מה כתוב בקובץ',
    sourceAt: (sheet: string | null, page: number | null, row: number | null) => {
      const parts: string[] = [];
      if (sheet !== null) parts.push(`גיליון ${sheet}`);
      if (page !== null) parts.push(`עמוד ${count(page)}`);
      if (row !== null) parts.push(`שורה ${count(row)}`);
      return parts.length === 0 ? 'מהקובץ' : parts.join(' · ');
    },
    duplicateOf: 'נראה כמו רשומה שכבר קיימת',
    duplicateLikely: 'כנראה כבר קיים',
    duplicatePossible: 'אולי כבר קיים',
    duplicateNew: 'חדש',
    approveTitle: 'לאשר את מה שסימנתם',
    approveExplain: (included: number) =>
      included === 1
        ? 'שורה אחת תיכנס לתמונה הפיננסית.'
        : `${count(included)} שורות ייכנסו לתמונה הפיננסית.`,
    approveBlocked: 'עוד אי אפשר לאשר',
    approvePending: (pending: number) =>
      pending === 1
        ? 'נשארה שורה אחת שעוד לא הוכרעה.'
        : `נשארו ${count(pending)} שורות שעוד לא הוכרעו.`,
    approveNoneIncluded: 'לא סומנה אף שורה להכנסה.',
    approveNeedsAccount: 'יש שורות שעוד לא ברור לאיזה חשבון הן שייכות.',
    approve: 'לאשר ולהכניס',
    reject: 'לא להשתמש בקובץ הזה',
    rejectHint: 'הקובץ יסומן כנדחה. שום דבר לא ייכנס.',
    approved: 'אושר',
    rejected: 'נדחה',
    failed: 'לא הצלחנו לקרוא',
    reversed: 'בוטל',
    resultTitle: 'מה השתנה',
    resultCreated: (created: number) =>
      created === 1 ? 'נוספה רשומה אחת.' : `נוספו ${count(created)} רשומות.`,
    accountChanged: (name: string, deltaMinor: number) =>
      deltaMinor < 0
        ? `${name}: ירד ב־${money(Math.abs(deltaMinor))}`
        : `${name}: עלה ב־${money(deltaMinor)}`,
    reverse: 'לבטל את היבוא הזה',
    reverseHint:
      'כל מה שהיבוא הזה הכניס יפסיק להיספר. מה שרשמתם בעצמכם לא ייגע. אפשר לראות את זה בהיסטוריה.',
    reverseReason: 'למה מבטלים',
    fileDeleted: 'הקובץ עצמו נמחק מהמחשב אחרי ההחלטה. נשארו רק השם, הגודל והתאריך.',
    warnings: {
      ambiguous_date: 'לא היה ברור אם התאריך הוא יום/חודש או חודש/יום.',
      ambiguous_column_mapping: 'לא היינו בטוחים מה כל עמודה אומרת.',
      ambiguous_direction: 'לא היה ברור אם הסכום נכנס או יצא.',
      unparsed_amount: 'הסכום היה כתוב בצורה לא ברורה.',
      missing_date: 'חסר תאריך.',
      missing_amount: 'חסר סכום.',
      missing_description: 'אין תיאור לשורה.',
      row_out_of_range: 'השורה מחוץ לטווח שקראנו.',
      repeated_header: 'הכותרת חוזרת באמצע הקובץ, ודילגנו עליה.',
      footer_total_row: 'שורת סיכום — לא נכנסת כתנועה.',
      formula_cell_value_used: 'בקובץ יש נוסחאות. לקחנו את הערך השמור, בלי להריץ אותן.',
      low_confidence_document_type: 'לא היינו בטוחים איזה סוג מסמך זה.',
      multiple_accounts_in_file: 'נראה שיש בקובץ יותר מחשבון אחד.',
      page_text_unreliable: 'ב־PDF קראנו טקסט בלבד, בלי לפרש את הפריסה של הדף.',
      image_only_page: 'יש עמודים שהם תמונה בלבד ואין בהם טקסט.',
      truncated_by_limit: 'הקובץ ארוך מדי, ולכן קראנו רק חלק ממנו.',
      currency_assumed: 'הנחנו שהמטבע הוא שקל.',
      balance_does_not_follow: 'היתרה בשורה הזו לא מסתדרת עם הקודמת.',
    } as Record<string, string>,
    failureCodes: {
      unsupported_file_type: 'סוג הקובץ אינו נתמך.',
      signature_mismatch: 'התוכן אינו מתאים לסיומת הקובץ.',
      file_too_large: 'הקובץ גדול מדי.',
      encrypted_file: 'הקובץ מוגן בסיסמה.',
      macro_enabled_file: 'הקובץ מכיל מאקרו, ולכן לא נפתח.',
      malformed_archive: 'הקובץ פגום.',
      malformed_document: 'לא הצלחנו לקרוא את המסמך.',
      no_text_layer: 'אין בקובץ טקסט לקריאה.',
      no_table_found: 'לא נמצאה טבלה בקובץ.',
      limit_exceeded: 'הקובץ מורכב מדי לקריאה.',
      extraction_timeout: 'הקריאה ארכה יותר מדי.',
    } as Record<string, string>,
  },

  tasks: {
    title: 'מה עושים',
    subtitle: 'הצעדים שהחלטתם עליהם, ומי לוקח כל אחד',
    empty: 'אין כרגע משימות פתוחות.',
    emptyHint: 'זה בסדר גמור. כשיהיה משהו שכדאי לעשות, הוא יופיע כאן.',
    add: 'להוסיף משימה',
    what: 'מה צריך לעשות',
    why: 'למה',
    who: 'מי',
    whoNobody: 'עוד לא החלטנו',
    due: 'עד מתי',
    amount: 'סכום',
    relatedDebt: 'קשור לחוב',
    open: 'פתוח',
    done: 'בוצע',
    dismissed: 'ויתרנו',
    markDone: 'סימון כבוצע',
    dismiss: 'לא רלוונטי',
    reopen: 'להחזיר לפתוח',
    followUp: 'לחזור לזה ב־',
    fromRecommendation: 'מתוך ההמלצה של המסך הראשי',
    addFromAction: 'להפוך את זה למשימה',
  },

  reports: {
    title: 'דוחות',
    subtitle: 'סיכומים שאפשר להסתכל עליהם, להדפיס או לשמור',
    month: 'סיכום החודש',
    budgetVsActual: 'תקציב מול מה שקרה',
    debtMap: 'מפת החובות',
    debtMovement: 'איך זזו החובות',
    business: 'סיכום העסק',
    yearToDate: 'מתחילת השנה',
    importHistory: 'קבצים שהעלינו',
    completeness: 'עד כמה התמונה מלאה',
    period: 'תקופה',
    generatedAt: (timestamp: string) => `הופק ב־${new Date(timestamp).toLocaleString('he-IL')}`,
    approvedOnly: 'הדוח כולל רק מה שאושר. מה שממתין לבדיקה אינו נספר.',
    pendingCount: (pending: number) =>
      pending === 0
        ? 'אין כרגע פריטים שממתינים לבדיקה.'
        : `${count(pending)} פריטים ממתינים לבדיקה ואינם נכללים בדוח.`,
    exportTitle: 'לשמור עותק',
    exportExcel: 'להוריד כקובץ Excel',
    exportCsv: 'להוריד כ־CSV',
    exportPdf: 'להדפיס או לשמור כ־PDF',
    exportPdfHint:
      'נפתח מסך הדפסה של הדפדפן. משם אפשר לבחור "שמירה כ־PDF" ולקבל קובץ עם עברית תקינה.',
    print: 'הדפסה',
    noData: 'אין עדיין מספיק נתונים לדוח הזה.',
    nothingThisMonth: 'החודש הזה עדיין ריק.',
  },

  backup: {
    title: 'גיבוי ושחזור',
    subtitle: 'עותק של הכול, שמור אצלכם',
    whatTitle: 'מה נכנס לגיבוי',
    whatBody:
      'חשבונות, יתרות, תנועות, חובות, תקציבים, משימות, היסטוריית היבוא וכל רישום הפעולות. אין בגיבוי סיסמאות או מפתחות, כי אין כאלה במערכת.',
    whereTitle: 'איפה הוא נשמר',
    whereBody: 'בתיקייה בתוך התוכנה, על המחשב הזה. שום דבר לא נשלח לשום מקום.',
    create: 'ליצור גיבוי עכשיו',
    created: 'הגיבוי נוצר',
    existing: 'גיבויים קיימים',
    noBackups: 'עוד לא יצרתם גיבוי.',
    restoreTitle: 'שחזור מגיבוי',
    restoreWarning:
      'שחזור מחליף את כל מה שקיים כאן בתוכן הגיבוי. לפני שנחליף, נראה לכם בדיוק מה יש בקובץ.',
    chooseFile: 'לבחור קובץ גיבוי',
    check: 'לבדוק את הקובץ',
    previewTitle: 'מה יש בגיבוי',
    previewCreated: (timestamp: string) =>
      `נוצר ב־${new Date(timestamp).toLocaleString('he-IL')}`,
    previewNow: 'מה יש כאן עכשיו',
    previewAfter: 'מה יהיה אחרי השחזור',
    confirmLabel: 'כדי לאשר, נא להקליד: שחזור',
    confirmWord: 'שחזור',
    apply: 'לשחזר',
    applied: 'השחזור הושלם',
    keptHistory: 'המצב הקודם נשמר בהיסטוריה המקומית, ליתר ביטחון.',
    counts: {
      accounts: 'חשבונות',
      transactions: 'תנועות',
      debts: 'חובות',
      budgets: 'תקציבים',
      importBatches: 'קבצים שיובאו',
      tasks: 'משימות',
      auditEntries: 'רישומי פעולות',
    } as Record<string, string>,
  },

  activity: {
    title: 'מה קרה כאן',
    subtitle: 'כל שינוי שנעשה, לפי הסדר',
    empty: 'עוד לא נעשה כאן שום שינוי.',
    actions: {
      'household.renamed': 'שם משק הבית שונה',
      'member.added': 'נוסף בן משפחה',
      'settings.updated': 'ההגדרות עודכנו',
      'account.added': 'נוסף חשבון',
      'account.closed': 'חשבון נסגר',
      'balance.confirmed': 'יתרה אושרה',
      'transaction.recorded': 'נרשמה תנועה',
      'transaction.voided': 'תנועה בוטלה',
      'planned_item.added': 'נוסף פריט צפוי',
      'planned_item.settled': 'פריט צפוי סומן כבוצע',
      'planned_item.removed': 'פריט צפוי הוסר',
      'debt.added': 'נוסף חוב',
      'debt_event.recorded': 'נרשם אירוע בחוב',
      'rollover.recorded': 'נרשמה החלפה בין חובות',
      'business.added': 'נוסף עסק',
      'business.declined': 'סומן שאין עסק',
      'budget.started': 'התחיל תקציב',
      'budget_line.added': 'נוספה קטגוריה לתקציב',
      'budget_line.changed': 'שונה סכום בתקציב',
      'task.added': 'נוספה משימה',
      'task.updated': 'משימה עודכנה',
      'import.staged': 'הועלה קובץ',
      'import.failed': 'קובץ לא נקרא',
      'import.row_reviewed': 'שורה ביבוא הוכרעה',
      'import.rows_reviewed': 'שורות ביבוא הוכרעו',
      'import.approved': 'יבוא אושר',
      'import.rejected': 'יבוא נדחה',
      'import.reversed': 'יבוא בוטל',
    } as Record<string, string>,
    filterAll: 'הכול',
    filterMoney: 'כסף בלבד',
    filterImports: 'יבוא בלבד',
  },

  approvals: {
    title: 'ממתין לאישור',
    subtitle: 'דברים שהמערכת מציעה, ושעדיין לא נכנסו לתמונה',
    empty: 'אין כרגע שום דבר שממתין לאישור.',
    emptyHint: 'כשתעלו קובץ, מה שיימצא בו יופיע כאן עד שתאשרו.',
    batchesTitle: 'קבצים שממתינים לבדיקה',
    draftsTitle: 'תנועות שנרשמו כטיוטה',
    review: 'לעבור על הקובץ',
    rows: (rows: number) => (rows === 1 ? 'שורה אחת' : `${count(rows)} שורות`),
    uploadedOn: (timestamp: string) =>
      `הועלה ב־${new Date(timestamp).toLocaleDateString('he-IL')}`,
  },

  settings: {
    title: 'הגדרות',
    subtitle: 'הדברים הבודדים שמשנים איך כל מספר נקרא',
    monthStart: 'היום שבו מתחיל אצלכם החודש',
    monthStartHint: 'אם המשכורת נכנסת ב־10, לרוב נוח לחשוב על חודש שמתחיל ב־10.',
    reserveTitle: 'כמה כסף להשאיר בצד',
    reserveHint:
      'הסכום שלא ייכנס לחישוב של "כמה אפשר להוציא". נבחר הגבוה מבין מה שתמלאו כאן ומה שהמערכת מחשבת מהצרכים החיוניים.',
    manualFloor: 'סכום שאתם קובעים',
    incidentBuffer: 'כמה תעלה תקלה סבירה',
    incidentBufferHint: 'למשל: תיקון רכב, מקרר שנשרף.',
    revolvingAvoidance: 'כמה צריך כדי לא לחזור למינוס',
    protectedReserves: 'כסף ששמור למטרה אחרת',
    protectedReservesHint: 'פיקדון שאתם מחזיקים, כסף שכבר יועד למשהו. הוא פשוט לא זמין.',
    notificationsTitle: 'תזכורות',
    notificationsHint: 'הכול מקומי. שום התראה לא נשלחת לשום מקום.',
    weeklyFood: 'להראות הנחיה שבועית לאוכל במסך הבית',
    freshnessReminder: 'להזכיר לעדכן יתרות',
    save: 'לשמור',
    dataTitle: 'הנתונים שלכם',
    dataLocation: 'הנתונים נשמרים כאן',
    dataLocationHint: 'תיקייה בתוך התוכנה, על המחשב הזה בלבד.',
  },

  offline: {
    title: 'אין כרגע חיבור',
    body: 'המסך הזה עובד מקומית, ולכן רוב הדברים ימשיכו לעבוד. אם משהו לא נטען, כדאי לרענן כשהחיבור חוזר.',
    lastUpdated: (timestamp: string) =>
      `הנתונים עודכנו לאחרונה ב־${new Date(timestamp).toLocaleString('he-IL')}`,
  },

  common: {
    required: 'שדה חובה',
    optional: 'לא חובה',
    saving: 'שומרים…',
    back: 'חזרה',
    next: 'הבא',
    skip: 'לדלג',
    yes: 'כן',
    no: 'לא',
    total: 'סך הכול',
    none: '—',
    show: 'להציג',
    hide: 'להסתיר',
    confirm: 'לאשר',
    delete: 'למחוק',
    fix: 'לתקן',
  },
} as const;

export type Screens = typeof screens;
