import { inflateSync } from 'node:zlib';

import { Deadline, LIMITS, LimitExceededError, MalformedDocumentError } from './limits';

/**
 * The object layer of a PDF, read defensively.
 *
 * A PDF is a graph of numbered objects with a cross-reference table pointing into
 * the file. Real statements from real banks routinely have a cross-reference table
 * that is wrong — regenerated by a signing tool, or truncated by an email
 * gateway — and a reader that trusts it fails on documents a person can open
 * perfectly well in a viewer.
 *
 * So this reader does not trust it. It scans the whole file for object headers and
 * builds its own index. That is slower than seeking, bounded by the file size
 * limit, and immune to a corrupt or hostile table. Where a PDF stores objects
 * inside compressed object streams (which is how anything modern is written), those
 * are expanded into the same index.
 *
 * Nothing here executes anything. JavaScript actions, embedded files, launch
 * actions and form logic are simply never looked at: only page content streams and
 * the font resources they name are read.
 */

export type PdfName = { readonly kind: 'name'; readonly value: string };
export type PdfRef = {
  readonly kind: 'ref';
  readonly number: number;
  readonly generation: number;
};
export type PdfDict = {
  readonly kind: 'dict';
  readonly entries: ReadonlyMap<string, PdfObject>;
};
export type PdfArray = { readonly kind: 'array'; readonly items: readonly PdfObject[] };
export type PdfStream = {
  readonly kind: 'stream';
  readonly dict: PdfDict;
  /** Raw, still-encoded bytes. Decoding happens on demand. */
  readonly raw: Uint8Array;
};

export type PdfObject =
  | { readonly kind: 'number'; readonly value: number }
  | { readonly kind: 'string'; readonly bytes: Uint8Array }
  | { readonly kind: 'boolean'; readonly value: boolean }
  | { readonly kind: 'null' }
  | PdfName
  | PdfRef
  | PdfDict
  | PdfArray
  | PdfStream;

const WHITESPACE = new Set([0x00, 0x09, 0x0a, 0x0c, 0x0d, 0x20]);
const DELIMITERS = new Set([0x28, 0x29, 0x3c, 0x3e, 0x5b, 0x5d, 0x7b, 0x7d, 0x2f, 0x25]);

function isWhitespace(byte: number | undefined): boolean {
  return byte !== undefined && WHITESPACE.has(byte);
}

function isDelimiter(byte: number | undefined): boolean {
  return byte !== undefined && DELIMITERS.has(byte);
}

/** A cursor over the file, producing one object at a time. */
export class PdfLexer {
  position: number;

  constructor(
    private readonly bytes: Uint8Array,
    start = 0,
  ) {
    this.position = start;
  }

  atEnd(): boolean {
    return this.position >= this.bytes.length;
  }

  skipWhitespace(): void {
    while (this.position < this.bytes.length) {
      const byte = this.bytes[this.position];
      if (isWhitespace(byte)) {
        this.position += 1;
        continue;
      }
      // A comment runs to the end of the line.
      if (byte === 0x25) {
        while (
          this.position < this.bytes.length &&
          this.bytes[this.position] !== 0x0a &&
          this.bytes[this.position] !== 0x0d
        ) {
          this.position += 1;
        }
        continue;
      }
      return;
    }
  }

  /** Reads the next token as raw text: a keyword, number, or delimiter run. */
  peekKeyword(): string {
    const saved = this.position;
    this.skipWhitespace();
    const start = this.position;
    while (
      this.position < this.bytes.length &&
      !isWhitespace(this.bytes[this.position]) &&
      !isDelimiter(this.bytes[this.position])
    ) {
      this.position += 1;
    }
    const keyword = latin1(this.bytes.subarray(start, this.position));
    this.position = saved;
    return keyword;
  }

  private readRegularToken(): string {
    const start = this.position;
    while (
      this.position < this.bytes.length &&
      !isWhitespace(this.bytes[this.position]) &&
      !isDelimiter(this.bytes[this.position])
    ) {
      this.position += 1;
    }
    return latin1(this.bytes.subarray(start, this.position));
  }

  /**
   * Reads one object.
   *
   * `depth` bounds nesting: a document that nests arrays ten thousand deep is
   * either broken or trying to exhaust the stack, and neither deserves recursion.
   */
  readObject(depth = 0): PdfObject {
    if (depth > 64) {
      throw new MalformedDocumentError(
        'malformed_document',
        'the object graph nests too deeply',
      );
    }

    this.skipWhitespace();
    if (this.atEnd()) return { kind: 'null' };

    const byte = this.bytes[this.position];

    if (byte === 0x2f) {
      this.position += 1;
      return { kind: 'name', value: this.readName() };
    }

    if (byte === 0x28) {
      this.position += 1;
      return { kind: 'string', bytes: this.readLiteralString() };
    }

    if (byte === 0x3c) {
      if (this.bytes[this.position + 1] === 0x3c) {
        this.position += 2;
        return this.readDictionaryOrStream(depth);
      }
      this.position += 1;
      return { kind: 'string', bytes: this.readHexString() };
    }

    if (byte === 0x5b) {
      this.position += 1;
      const items: PdfObject[] = [];
      for (;;) {
        this.skipWhitespace();
        if (this.atEnd()) break;
        if (this.bytes[this.position] === 0x5d) {
          this.position += 1;
          break;
        }
        items.push(this.readObject(depth + 1));
        if (items.length > 100_000) {
          throw new LimitExceededError('maxPdfObjects', 'an array is implausibly long');
        }
      }
      return { kind: 'array', items };
    }

    if (byte === 0x5d || byte === 0x3e || byte === 0x29 || byte === 0x7d) {
      // A stray closing delimiter. Consume it so the caller cannot spin.
      this.position += 1;
      return { kind: 'null' };
    }

    const token = this.readRegularToken();

    if (token === 'true') return { kind: 'boolean', value: true };
    if (token === 'false') return { kind: 'boolean', value: false };
    if (token === 'null' || token === '') return { kind: 'null' };

    if (/^[+-]?[\d.]+$/.test(token)) {
      const value = Number.parseFloat(token);
      // `12 0 R` is an indirect reference, and only integers can start one.
      if (Number.isInteger(value) && value >= 0) {
        const afterNumber = this.position;
        this.skipWhitespace();
        const generationToken = this.readRegularToken();
        if (/^\d+$/.test(generationToken)) {
          this.skipWhitespace();
          if (this.readRegularToken() === 'R') {
            return { kind: 'ref', number: value, generation: Number(generationToken) };
          }
        }
        // Not a reference after all: the number stands alone.
        this.position = afterNumber;
      }
      return { kind: 'number', value: Number.isFinite(value) ? value : 0 };
    }

    // An unrecognised keyword (`obj`, `endobj`, an operator) is not an object.
    return { kind: 'null' };
  }

  private readName(): string {
    const start = this.position;
    while (
      this.position < this.bytes.length &&
      !isWhitespace(this.bytes[this.position]) &&
      !isDelimiter(this.bytes[this.position])
    ) {
      this.position += 1;
    }
    const raw = latin1(this.bytes.subarray(start, this.position));
    // `#20` is an escaped byte inside a name.
    return raw.replace(/#([0-9a-fA-F]{2})/g, (_match, hex: string) =>
      String.fromCharCode(Number.parseInt(hex, 16)),
    );
  }

  private readLiteralString(): Uint8Array {
    const out: number[] = [];
    let nesting = 1;

    while (this.position < this.bytes.length) {
      const byte = this.bytes[this.position];
      this.position += 1;

      if (byte === 0x5c) {
        const escaped = this.bytes[this.position];
        this.position += 1;
        switch (escaped) {
          case 0x6e:
            out.push(0x0a);
            break;
          case 0x72:
            out.push(0x0d);
            break;
          case 0x74:
            out.push(0x09);
            break;
          case 0x62:
            out.push(0x08);
            break;
          case 0x66:
            out.push(0x0c);
            break;
          case 0x0a:
            break;
          case 0x0d:
            if (this.bytes[this.position] === 0x0a) this.position += 1;
            break;
          default: {
            if (escaped !== undefined && escaped >= 0x30 && escaped <= 0x37) {
              let octal = escaped - 0x30;
              for (let extra = 0; extra < 2; extra += 1) {
                const next = this.bytes[this.position];
                if (next === undefined || next < 0x30 || next > 0x37) break;
                octal = octal * 8 + (next - 0x30);
                this.position += 1;
              }
              out.push(octal & 0xff);
            } else if (escaped !== undefined) {
              out.push(escaped);
            }
          }
        }
        continue;
      }

      if (byte === 0x28) nesting += 1;
      if (byte === 0x29) {
        nesting -= 1;
        if (nesting === 0) break;
      }
      if (byte !== undefined) out.push(byte);

      if (out.length > 1_000_000) {
        throw new LimitExceededError('maxPdfPageChars', 'a string literal is implausibly long');
      }
    }

    return Uint8Array.from(out);
  }

  private readHexString(): Uint8Array {
    const digits: string[] = [];
    while (this.position < this.bytes.length) {
      const byte = this.bytes[this.position];
      this.position += 1;
      if (byte === 0x3e) break;
      const character = String.fromCharCode(byte ?? 0);
      if (/[0-9a-fA-F]/.test(character)) digits.push(character);
    }
    if (digits.length % 2 === 1) digits.push('0');

    const out = new Uint8Array(digits.length / 2);
    for (let index = 0; index < out.length; index += 1) {
      out[index] = Number.parseInt(`${digits[index * 2]}${digits[index * 2 + 1]}`, 16);
    }
    return out;
  }

  private readDictionaryOrStream(depth: number): PdfObject {
    const entries = new Map<string, PdfObject>();

    for (;;) {
      this.skipWhitespace();
      if (this.atEnd()) break;

      if (this.bytes[this.position] === 0x3e && this.bytes[this.position + 1] === 0x3e) {
        this.position += 2;
        break;
      }

      if (this.bytes[this.position] !== 0x2f) {
        // Not a key: skip a byte so a malformed dictionary cannot loop forever.
        this.position += 1;
        continue;
      }

      this.position += 1;
      const key = this.readName();
      const value = this.readObject(depth + 1);
      entries.set(key, value);

      if (entries.size > 4096) {
        throw new LimitExceededError('maxPdfObjects', 'a dictionary is implausibly large');
      }
    }

    const dict: PdfDict = { kind: 'dict', entries };

    const saved = this.position;
    this.skipWhitespace();
    if (this.matchKeyword('stream')) {
      // The keyword is followed by CRLF or LF, and the data starts immediately after.
      if (this.bytes[this.position] === 0x0d) this.position += 1;
      if (this.bytes[this.position] === 0x0a) this.position += 1;

      const start = this.position;
      const declaredLength = entries.get('Length');
      let end = -1;

      if (declaredLength?.kind === 'number' && declaredLength.value >= 0) {
        const candidate = start + declaredLength.value;
        if (candidate <= this.bytes.length && this.looksLikeStreamEnd(candidate)) {
          end = candidate;
        }
      }

      if (end === -1) {
        // The declared length is missing, indirect, or wrong. Find the terminator.
        end = this.findKeyword('endstream', start);
        if (end === -1) {
          throw new MalformedDocumentError('malformed_document', 'a stream is never closed');
        }
        // Trim the newline the writer put before `endstream`.
        let trimmed = end;
        if (this.bytes[trimmed - 1] === 0x0a) trimmed -= 1;
        if (this.bytes[trimmed - 1] === 0x0d) trimmed -= 1;
        end = trimmed;
      }

      this.position = this.findKeyword('endstream', end);
      this.position = this.position === -1 ? this.bytes.length : this.position + 9;

      return { kind: 'stream', dict, raw: this.bytes.subarray(start, end) };
    }

    this.position = saved;
    return dict;
  }

  private looksLikeStreamEnd(offset: number): boolean {
    const probe = new PdfLexer(this.bytes, offset);
    probe.skipWhitespace();
    return probe.peekKeyword() === 'endstream';
  }

  private matchKeyword(keyword: string): boolean {
    const start = this.position;
    for (let index = 0; index < keyword.length; index += 1) {
      if (this.bytes[start + index] !== keyword.charCodeAt(index)) return false;
    }
    this.position = start + keyword.length;
    return true;
  }

  private findKeyword(keyword: string, from: number): number {
    const first = keyword.charCodeAt(0);
    for (let index = from; index <= this.bytes.length - keyword.length; index += 1) {
      if (this.bytes[index] !== first) continue;
      let matched = true;
      for (let offset = 1; offset < keyword.length; offset += 1) {
        if (this.bytes[index + offset] !== keyword.charCodeAt(offset)) {
          matched = false;
          break;
        }
      }
      if (matched) return index;
    }
    return -1;
  }
}

/** Bytes as Latin-1 text. PDF syntax is ASCII; this never touches page content. */
export function latin1(bytes: Uint8Array): string {
  let text = '';
  for (const byte of bytes) text += String.fromCharCode(byte);
  return text;
}

/**
 * The whole document, indexed.
 *
 * `resolve` follows indirect references, with a visited set so a cycle — which a
 * malformed or hostile file can contain — terminates instead of recursing.
 */
export class PdfDocument {
  private readonly objects = new Map<number, PdfObject>();

  private constructor(
    private readonly bytes: Uint8Array,
    readonly encrypted: boolean,
  ) {}

  static parse(bytes: Uint8Array, deadline = new Deadline()): PdfDocument {
    // One Latin-1 view of the file, reused: building it twice over a twenty
    // megabyte upload is a measurable cost for no benefit.
    const text = latin1(bytes);
    const encrypted = /\/Encrypt\s+\d+\s+\d+\s+R/.test(text) || /\/Encrypt\s*<</.test(text);
    const document = new PdfDocument(bytes, encrypted);

    if (encrypted) return document;

    document.indexObjects(text, deadline);
    document.expandObjectStreams(deadline);
    return document;
  }

  /** Scans for `N G obj` headers and parses each object that follows. */
  private indexObjects(text: string, deadline: Deadline): void {
    const pattern = /(\d{1,10})\s+(\d{1,5})\s+obj\b/g;
    let match = pattern.exec(text);
    let count = 0;

    while (match !== null) {
      if ((count & 0x3ff) === 0) deadline.check();
      count += 1;
      if (count > LIMITS.maxPdfObjects) {
        throw new LimitExceededError('maxPdfObjects', `${count} objects`);
      }

      const number = Number(match[1]);
      const bodyStart = match.index + match[0].length;

      try {
        const lexer = new PdfLexer(this.bytes, bodyStart);
        const object = lexer.readObject();
        // A later definition of the same object number supersedes an earlier one,
        // which is how incremental updates work.
        this.objects.set(number, object);
      } catch (error) {
        if (error instanceof LimitExceededError) throw error;
        // One unreadable object must not cost the whole document.
      }

      match = pattern.exec(text);
    }
  }

  /** Expands `/Type /ObjStm` containers into the same index. */
  private expandObjectStreams(deadline: Deadline): void {
    const containers = [...this.objects.values()].filter(
      (object): object is PdfStream =>
        object.kind === 'stream' && nameOf(object.dict.entries.get('Type')) === 'ObjStm',
    );

    for (const container of containers) {
      deadline.check();
      let decoded: Uint8Array;
      try {
        decoded = this.decodeStream(container);
      } catch {
        continue;
      }

      const count = numberOf(this.resolve(container.dict.entries.get('N'))) ?? 0;
      const first = numberOf(this.resolve(container.dict.entries.get('First'))) ?? 0;
      if (count <= 0 || first <= 0 || first > decoded.length) continue;

      const header = latin1(decoded.subarray(0, first));
      const numbers = header.trim().split(/\s+/).map(Number);

      for (let index = 0; index < count; index += 1) {
        const objectNumber = numbers[index * 2];
        const offset = numbers[index * 2 + 1];
        if (objectNumber === undefined || offset === undefined) break;
        if (!Number.isFinite(objectNumber) || !Number.isFinite(offset)) break;
        // Objects already defined outside a stream win: they come from a later
        // incremental update.
        if (this.objects.has(objectNumber)) continue;
        try {
          const lexer = new PdfLexer(decoded, first + offset);
          this.objects.set(objectNumber, lexer.readObject());
        } catch {
          // Skip the one entry, keep the rest.
        }
      }
    }
  }

  resolve(object: PdfObject | undefined, depth = 0): PdfObject | undefined {
    if (object === undefined) return undefined;
    if (object.kind !== 'ref') return object;
    if (depth > 32) return undefined;
    return this.resolve(this.objects.get(object.number), depth + 1);
  }

  /** Every object in the document, for the page walk. */
  entries(): ReadonlyMap<number, PdfObject> {
    return this.objects;
  }

  /**
   * Decodes a stream's filters.
   *
   * Only the filters a text-bearing page actually uses are implemented. An image
   * filter (`DCTDecode`, `JPXDecode`, `CCITTFaxDecode`) is not decoded at all —
   * there is no text in a photograph, and running an image codec over untrusted
   * bytes buys nothing but risk.
   */
  decodeStream(stream: PdfStream): Uint8Array {
    const filterEntry = this.resolve(stream.dict.entries.get('Filter'));
    const filters: string[] = [];

    if (filterEntry?.kind === 'name') filters.push(filterEntry.value);
    if (filterEntry?.kind === 'array') {
      for (const item of filterEntry.items) {
        const resolved = this.resolve(item);
        if (resolved?.kind === 'name') filters.push(resolved.value);
      }
    }

    let data = stream.raw;

    for (const filter of filters) {
      if (filter === 'FlateDecode') {
        data = inflate(data);
        continue;
      }
      if (filter === 'ASCIIHexDecode') {
        data = asciiHexDecode(data);
        continue;
      }
      if (filter === 'ASCII85Decode') {
        data = ascii85Decode(data);
        continue;
      }
      if (filter === 'RunLengthDecode') {
        data = runLengthDecode(data);
        continue;
      }
      // Anything else — image codecs, encryption filters — yields no text.
      return new Uint8Array(0);
    }

    const predicted = this.applyPredictor(stream, data);
    return predicted;
  }

  /**
   * Undoes the PNG predictor some writers apply before compressing.
   *
   * Without this, a cross-reference or object stream written by a modern producer
   * decodes to bytes that are shifted by the previous row and parse as nonsense.
   */
  private applyPredictor(stream: PdfStream, data: Uint8Array): Uint8Array {
    const parms = this.resolve(stream.dict.entries.get('DecodeParms'));
    const dict = parms?.kind === 'dict' ? parms : undefined;
    if (dict === undefined) return data;

    const predictor = numberOf(this.resolve(dict.entries.get('Predictor'))) ?? 1;
    if (predictor < 10) return data;

    const colours = numberOf(this.resolve(dict.entries.get('Colors'))) ?? 1;
    const bits = numberOf(this.resolve(dict.entries.get('BitsPerComponent'))) ?? 8;
    const columns = numberOf(this.resolve(dict.entries.get('Columns'))) ?? 1;
    const bytesPerPixel = Math.max(1, Math.ceil((colours * bits) / 8));
    const rowLength = Math.ceil((colours * bits * columns) / 8);

    if (rowLength <= 0 || rowLength > 1_000_000) return data;

    const rows = Math.floor(data.length / (rowLength + 1));
    const out = new Uint8Array(rows * rowLength);
    let previous = new Uint8Array(rowLength);

    for (let row = 0; row < rows; row += 1) {
      const tag = data[row * (rowLength + 1)] ?? 0;
      const source = data.subarray(row * (rowLength + 1) + 1, (row + 1) * (rowLength + 1));
      const current = new Uint8Array(rowLength);

      for (let index = 0; index < rowLength; index += 1) {
        const raw = source[index] ?? 0;
        const left = index >= bytesPerPixel ? (current[index - bytesPerPixel] ?? 0) : 0;
        const up = previous[index] ?? 0;
        const upLeft = index >= bytesPerPixel ? (previous[index - bytesPerPixel] ?? 0) : 0;

        let value: number;
        switch (tag) {
          case 0:
            value = raw;
            break;
          case 1:
            value = raw + left;
            break;
          case 2:
            value = raw + up;
            break;
          case 3:
            value = raw + Math.floor((left + up) / 2);
            break;
          case 4: {
            const p = left + up - upLeft;
            const pa = Math.abs(p - left);
            const pb = Math.abs(p - up);
            const pc = Math.abs(p - upLeft);
            value = raw + (pa <= pb && pa <= pc ? left : pb <= pc ? up : upLeft);
            break;
          }
          default:
            value = raw;
        }
        current[index] = value & 0xff;
      }

      out.set(current, row * rowLength);
      previous = current;
    }

    return out;
  }
}

function inflate(data: Uint8Array): Uint8Array {
  try {
    const result = inflateSync(data, { maxOutputLength: LIMITS.maxInflatedBytes });
    return new Uint8Array(result.buffer, result.byteOffset, result.byteLength);
  } catch {
    return new Uint8Array(0);
  }
}

function asciiHexDecode(data: Uint8Array): Uint8Array {
  const digits: string[] = [];
  for (const byte of data) {
    const character = String.fromCharCode(byte);
    if (character === '>') break;
    if (/[0-9a-fA-F]/.test(character)) digits.push(character);
  }
  if (digits.length % 2 === 1) digits.push('0');
  const out = new Uint8Array(digits.length / 2);
  for (let index = 0; index < out.length; index += 1) {
    out[index] = Number.parseInt(`${digits[index * 2]}${digits[index * 2 + 1]}`, 16);
  }
  return out;
}

function ascii85Decode(data: Uint8Array): Uint8Array {
  const out: number[] = [];
  let group: number[] = [];

  for (let index = 0; index < data.length; index += 1) {
    const byte = data[index] ?? 0;
    if (byte === 0x7e) break; // `~>` terminator
    if (WHITESPACE.has(byte)) continue;
    if (byte === 0x7a && group.length === 0) {
      out.push(0, 0, 0, 0);
      continue;
    }
    if (byte < 0x21 || byte > 0x75) continue;

    group.push(byte - 0x21);
    if (group.length === 5) {
      let value = 0;
      for (const digit of group) value = value * 85 + digit;
      out.push(
        (value >>> 24) & 0xff,
        (value >>> 16) & 0xff,
        (value >>> 8) & 0xff,
        value & 0xff,
      );
      group = [];
    }
    if (out.length > LIMITS.maxInflatedBytes) break;
  }

  if (group.length > 1) {
    const padding = 5 - group.length;
    for (let index = 0; index < padding; index += 1) group.push(84);
    let value = 0;
    for (const digit of group) value = value * 85 + digit;
    const bytes = [
      (value >>> 24) & 0xff,
      (value >>> 16) & 0xff,
      (value >>> 8) & 0xff,
      value & 0xff,
    ];
    out.push(...bytes.slice(0, 4 - padding));
  }

  return Uint8Array.from(out);
}

function runLengthDecode(data: Uint8Array): Uint8Array {
  const out: number[] = [];
  let index = 0;
  while (index < data.length) {
    const length = data[index] ?? 128;
    index += 1;
    if (length === 128) break;
    if (length < 128) {
      for (let offset = 0; offset <= length; offset += 1) out.push(data[index + offset] ?? 0);
      index += length + 1;
    } else {
      const byte = data[index] ?? 0;
      for (let repeat = 0; repeat < 257 - length; repeat += 1) out.push(byte);
      index += 1;
    }
    if (out.length > LIMITS.maxInflatedBytes) break;
  }
  return Uint8Array.from(out);
}

export function nameOf(object: PdfObject | undefined): string | null {
  return object?.kind === 'name' ? object.value : null;
}

export function numberOf(object: PdfObject | undefined): number | null {
  return object?.kind === 'number' ? object.value : null;
}

export function dictOf(object: PdfObject | undefined): PdfDict | null {
  if (object?.kind === 'dict') return object;
  if (object?.kind === 'stream') return object.dict;
  return null;
}
