/**
 * Regression guard for framework-generated agent instruction files (ADR-0012).
 *
 * `next dev` writes AGENTS.md and CLAUDE.md into the Next project directory unless
 * `agentRules: false` is set. This repository keeps its constitution in CLAUDE.md at the
 * root, and no dependency may author instruction files inside it.
 *
 * This test asserts the configuration that prevents regeneration, and that no such file
 * is present anywhere in the project. It does not start a dev server — that verification
 * was performed against a running server and is recorded in docs/checkpoints/milestone-1.md.
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, test } from 'vitest';

import nextConfig from '../apps/web/next.config.ts';

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url));

/** Instruction files a framework may try to author. */
const GENERATED_AGENT_FILES = ['AGENTS.md', 'CLAUDE.md'];

/** The one CLAUDE.md that legitimately exists: the project constitution. */
const CONSTITUTION = join(REPO_ROOT, 'CLAUDE.md');

/** Directories that may contain a Next project. */
function projectDirs() {
  const dirs = [];
  for (const group of ['apps', 'packages']) {
    const groupDir = join(REPO_ROOT, group);
    if (!existsSync(groupDir)) continue;
    for (const entry of readdirSync(groupDir, { withFileTypes: true })) {
      if (entry.isDirectory()) dirs.push(join(groupDir, entry.name));
    }
  }
  return dirs;
}

describe('generation is disabled in the Next configuration', () => {
  test('agentRules is explicitly false', () => {
    expect(nextConfig.agentRules).toBe(false);
  });

  test('it is false, not merely falsy or absent', () => {
    expect(nextConfig.agentRules).not.toBeUndefined();
    expect(typeof nextConfig.agentRules).toBe('boolean');
  });

  test('the source file states the setting literally', () => {
    const source = readFileSync(join(REPO_ROOT, 'apps', 'web', 'next.config.ts'), 'utf8');
    expect(source).toMatch(/agentRules:\s*false/);
  });
});

describe('no generated instruction file exists in the project', () => {
  test.each(projectDirs().flatMap((dir) => GENERATED_AGENT_FILES.map((f) => [dir, f])))(
    '%s has no %s',
    (dir, file) => {
      const path = join(dir, file);
      expect(
        existsSync(path),
        `${path} exists. It is generated by a dependency, not authored by this project. Delete it and confirm agentRules is false.`,
      ).toBe(false);
    },
  );

  test('the repository root has no AGENTS.md', () => {
    expect(existsSync(join(REPO_ROOT, 'AGENTS.md'))).toBe(false);
  });
});

describe('the root constitution is intact', () => {
  const text = readFileSync(CONSTITUTION, 'utf8');

  test('exists and is the project constitution, not a generated pointer', () => {
    expect(existsSync(CONSTITUTION)).toBe(true);
    // The generated variant is the single line `@AGENTS.md`.
    expect(text.trim()).not.toBe('@AGENTS.md');
    expect(text.length).toBeGreaterThan(1000);
  });

  test('still carries its defining sections', () => {
    expect(text).toContain('# CLAUDE.md');
    expect(text).toContain('אין השלמה מדומה');
    expect(text).toContain('Local machine safety boundary');
  });

  test('carries no framework-managed block', () => {
    expect(text).not.toContain('BEGIN:nextjs-agent-rules');
  });
});
